name: semif
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - colormap==1.0.6
    - dacite==1.8.1
    - easydev==0.12.1
    - ExifRead==3.0.0
    - extcolors==1.0.0
    - fiona==1.9.5
    - geopandas==0.14.2
    - hydra-core==1.3.2
    - ipykernel==6.29.0
    - matplotlib==3.8.2
    - matplotlib-inline==0.1.6
    - numpy==1.26.3
    - omegaconf==2.3.0
    - opencv-python==4.9.0.80
    - pandas==2.2.0
    - piexif==1.1.3
    - pyshp==2.3.1
    - PyYAML==6.0.1
    - scikit-image==0.22.0
    - scikit-learn==1.4.0
    - scipy==1.12.0
    - seaborn==0.13.2
    - shapely==2.0.2
    - shyaml==0.6.2
    - tqdm==4.66.1