# See README for instructions
name: semif_nogpu
channels:
  - pytorch
  - conda-forge
  - conda-forge/label/dev
dependencies:
  - python==3.9
  - pip
  - pytorch::cpuonly
  - pytorch::pytorch
  - pytorch::torchvision
  - pip:
    - dacite
    - exifread
    - hydra-core
    - matplotlib
    - omegaconf
    - opencv-python
    - numpy
    - pandas
    - pyyaml
    - rasterio
    - requests
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - tqdm
    - pyshp
    - ipykernel
