name: semifff
channels:
  - pytorch
  - conda-forge
  - conda-forge/label/dev
dependencies:
  - python==3.9
  - pip
  - cudatoolkit==11.3.1
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::geopandas
  - pip:
    - colormap==1.0.4
    - dacite==1.8.0
    - easydev==0.12.0
    - exifread==3.0.0
    - extcolors==1.0.0
    - Fiona==1.9.0
    - hydra-core==1.2
    - matplotlib==3.6.2
    - omegaconf==2.3
    - opencv-python==4.7.0.68
    - numpy==1.23.4
    - pandas==1.5.1
    - pyyaml==6.0
    - rasterio==1.3.4
    - requests
    - scikit-image==0.19.3
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - seaborn==0.12.1
    - tqdm==4.64.1
    - pyshp==2.3.1
    - shapely==1.8.5
    - ipykernel==6.17.1