channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - hydra-core
  - seaborn
  - tqdm
  - matplotlib
  - opencv-python
  - pandas
  - exifread
  - piexif
  - pillow
  - scikit-learn
  - scikit-image
  - geopandas
  - dacite
  - pip
  - pip:
      - azure-core==1.31.0
      - azure-storage-blob==12.23.1
      - metashape==2.1.3
      - rawpy==0.23.1
      - seaborn==0.13.2