name: semif_assign_species 
#Conda env minimum for assign species
dependencies:
  - python=3.10
  - pip
  - pytorch::torchvision
  - conda-forge::geopandas
  - pip:
    - colormap==1.0.4
    - dacite==1.8.0
    - easydev==0.12.0
    - exifread==3.0.0
    - extcolors==1.0.0
    - fiona==1.9.0
    - hydra-core==1.2
    - omegaconf==2.3
    - opencv-python==4.7.0.68
    - rasterio==1.3.4
    - scikit-image==0.19.3
    - tqdm==4.64.1
    - pyshp==2.3.1
    - shapely==1.8.5