defaults:
  - synth: default
  - _self_

hydra:
  run:
    dir: ./
  output_subdir: 

general:
  save_to_database: True
  from_database: False
  db: test  # test, trial, WIR
  from_db: ${general.db}
  multitask: False
  multitasks: [localize_plants, remap_labels, segment_vegetation, synthesize] 
  task: synthesize  # localize_plants, remap_labels, segment_vegetation, synthesize
  workdir: ${hydra:runtime.cwd}  # where the code is executed

data:
  datadir: ${general.workdir}/blob_container
  developeddir: ${data.datadir}/semifield-developed-images-trial
  batchdir: ${data.developeddir}/NC_2022-03-29 # Is overiden by shell script
  cutoutdir: ${data.datadir}/semifield-cutouts-trial
  synthdir: ${data.datadir}/semifield-synthetic-images-trial
  modeldir: ${data.datadir}/semifield-models-trial

detect:
  model_path: ${data.modeldir}/plant_detector/best.pt
  detections_csv: ${data.batchdir}/autosfm
  save_detection: False

autosfm:
  autosfmdir: ${data.batchdir}/autosfm

segment:  # Segment Vegetation
  clear_border: True
  save_mask: False # Not implemented
  vi: exg
  class_algorithm: kmeans
  num_classes: 1