# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - movedata: movedata
  - asfm: asfm
  - inspect: inspect
# ancillary configs
  - segment: segment
  - validate: validate
  - override hydra/job_logging: custom # custom logging 
  - _self_

hydra:
  run:
    # dir: ./outputs
    dir: ${logs.logdir}/${job.jobname}/${general.batch_id}/${job.job_now}
    # dir: ${logs.logdir}/${job.jobname}
  output_subdir: ${hydra.run.dir}/hydra

# Required config. Only change these.
#----------------------------------------------------
general:
  # season: summer_weeds_2022
  # season: summer_cash_crops_2023
  season: summer_weeds_2023 # Before 2023-08-09 for TX summer weeds 2023 and all other locations
  # season: summer_weeds_2023_TXpos2 # Everything after 2023-08-29 for TX summer weeds 2023
  # season: cool_season_covers_2022_2023
  # season: cool_season_cover_2022_2023_MD_pos_2
  # season: cool_season_cover_2022_2023_MD_pos_3 # used only for MD_2023-03-16
  # season: cool_season_covers_2023_2024
  # season: summer_weeds_2024
#----------------------------------------------------
  metashape_key: ??? # Do not put key in the config since the file is committed to GitHub
  batch_id: ???
  # Main working directory 
  workdir: ${hydra:runtime.cwd}  # where the code is executed
  cpu_denominator: 4

# Select sections of pipeline to run
pipeline:
  download_data: False
  autosfm_pipeline: False
  localize_plants: False
  remap_labels: False
  assign_species: False
  segment_vegetation: True
  reformat_fullsizedmetadata: True
  validate: True
  repo_overview: False
  compare_blobs: False
  
# Other job/naming options (currently not used)
job:
  jobname: ${general.season}
  job_now: &nowdir ${now:%Y-%m-%d}/${now:%H:%M:%S}
  jobdir: ${data.datadir}/${job.jobname}/${job.job_now}

blob_names: # directory names in SemiF-AP/data that mimic blob container structure
  upload: semifield-upload
  developed: semifield-developed-images
  utils: semifield-utils
  cutout: semifield-cutouts
  model: semifield-models

# temp data locations (SemiFAnnotationPipeline/data/)
data:
  # Main data folders (replicates blob container naming)
  datadir: ${general.workdir}/data
  developeddir: ${data.datadir}/${blob_names.developed}
  cutoutdir: ${data.datadir}/${blob_names.cutout}
  modeldir: ${data.datadir}/${blob_names.model}
  utilsdir: ${data.datadir}/${blob_names.utils}
  # Logs
  logdir: ${general.workdir}/logs
  # Batch directory
  batchdir: ${data.developeddir}/${general.batch_id} 
  # All species information
  species: ${data.utilsdir}/species_information/species_info.json
  species_poly: ${data.utilsdir}/autosfm/ShapeFiles/${general.season}/${general.season}.shp
  # Ground control points directory
  gcp_dir: ${data.datadir}/${blob_names.utils}/autosfm/GroundControlPoints/${general.season}
  gcp_ref: None
  repo_database: ${general.workdir}/repo_overview
  database_parquet: ${data.repo_database}/database
  longterm_storage : /mnt/research-projects/s/screberg/longterm_images

pipeline_keys: ${general.workdir}/keys/pipeline_keys.yaml
  
  
# Batch sub-directories
batchdata:
  images: ${data.batchdir}/images #preprocessed images
  masks: ${data.batchdir}/masks #blue bbot pixel masks
  plant_dects: ${data.batchdir}/plant-detections # Skovsen et al. pre-inferenced detection if available
  autosfm: ${data.batchdir}/autosfm # asfm batch dir
  metadata: ${data.batchdir}/metadata # metadata created from remap
  meta_masks: ${data.batchdir}/meta_masks # created from segment vegetation
  batchmeta: ${data.batchdir}/${general.batch_id}.json # created from seg veg
  cutouts: ${data.cutoutdir}/${general.batch_id}

logs:
  logdir: ${general.workdir}/.batchlogs
  processed: ${logs.logdir}/processed.txt
  unprocessed: ${logs.logdir}/unprocessed.txt
  preprocessed_backlog: ${logs.logdir}/preprocessed_backlog.txt


date_ranges:
  MD:
    weeds 2022:
      start: "2022-03-04"
      end: "2022-09-17"
    cover crops 2022/2023:
      start: "2022-10-20"
      end: "2023-04-25"
    cash crops 2023:
      start: "2023-05-12"
      end: "2023-07-07"
    weeds 2023:
      start: "2023-07-17"
      end: "2023-09-17"
    cover crops 2023/2024:
      start: "2023-09-18"
      end: "2024-05-16"
    weeds 2024:
      start: "2024-07-08"
      end: "2024-09-08"

  NC:
    weeds 2022:
      start: "2022-03-04"
      end: "2022-09-23"
    cover crops 2022/2023:
      start: "2022-10-11"
      end: "2023-03-30"
    cash crops 2023:
      start: "2023-06-06"
      end: "2023-07-25"
    weeds 2023:
      start: "2023-08-21"
      end: "2023-10-10"
    cover crops 2023/2024:
      start: "2023-10-11"
      end: "2024-03-14"
    weeds 2024:
      start: "2024-07-08"
      end: "2024-10-08"

  TX:
    weeds 2022:
      start: "2022-03-04"
      end: "2022-10-24"
    cover crops 2022/2023:
      start: "2022-10-25"
      end: "2023-04-04"
    cash crops 2023:
      start: "2023-05-08"
      end: "2023-08-01"
    weeds 2023:
      start: "2023-08-04"
      end: "2023-10-19"
    cover crops 2023/2024:
      start: "2023-10-20"
      end: "2024-03-01"
    weeds 2024:
      start: "2024-03-26"
      end: "2024-09-08"
