general:
  batch_id: NC_2022-04-12
  save_to_database: False
  db: test  # test, trial, WIR
  multitask: False
  multitasks: [auto_sfm, localize_plants, remap_labels, segment_vegetation]
  task: auto_sfm  # test_mongodb, , segment_vegetation, localize_plants, remap_labels, auto_sfm
  workdir: ${hydra:runtime.cwd}  # where the code is executed
  datadir: ${general.workdir}/data
  trialdir: ${general.datadir}/trial
  batchdir: ${general.trialdir}/${general.batch_id}
  imagedir: ${general.batchdir}/developed
  logdir: ${general.workdir}/logs

detect:
  model_path: ${general.workdir}/models/plant_detector/exp/weights/best.pt
  detections_csv: ${general.batchdir}/detections.csv
  save_detection: False
  detectioncropdir: ${general.imagedir} # Location to save detection crops

autosfm:
  autosfmdir: ${general.batchdir}/autosfm

  # A volume directory to be mounted onto the Docker container running the autoSfM code
  autosfm_volume: ${general.workdir}/autosfm/volumes
  autosfm_storage: ${general.trialdir}
  autosfm_exports: ${general.workdir}/autosfm/exports

  config_save_path: ${autosfm.autosfm_volume}/config/config.yml
  config_copy_path: ${general.logdir}/autosfm/config_${general.batch_id}.yml

  # Do not put key in the config since the file is committed to GitHub
  metashape_key: ??? # NOTE: ??? is a special syntax. Do not remove.

  autosfm_config:
    # Required config
    export_path: "/home/psi_docker/autoSfM/exports" # Path in the Docker container
    storage_path: "/home/psi_docker/autoSfM/storage" # Path in the Docker container
    batch_id: ${general.batch_id}
    # Electives
    downscale:
      enabled: True
      factor: 0.1 # between (0, 1]

    align_photos:
      downscale: 1 # Accuracy parameter, lower means higher accuracy
      autosave: True

    depth_map:
      enabled: True
      downscale: 4
      autosave: True

    dense_cloud:
      enabled: True
      autosave: True

    dem: 
      enabled: True
      autosave: True

    orthomosaic:
      enabled: True
      export: 
        enabled: True
      autosave: True

    camera_fov:
      enabled: True

segment:  # Segment Vegetation
  clear_border: True
  cutoutdir: ${general.batchdir}/cutouts
  save_mask: False # Not implemented
  vi: exg
  class_algorithm: kmeans
  num_classes: 1
