# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - movedata: movedata
  - asfm: asfm
  - semif: semif
  - inspect: inspect
# ancillary configs
  - detect: detect
  - segment: segment
  - planting: planting # Planting dates
  - cutouts: cutouts
  - override hydra/job_logging: custom # custom logging 
  - _self_

hydra:
  searchpath: # Search for config in other repos
      # You can also use file based schema:
      - file://MoveData/conf
      - file://autoSfM/conf
      - file://SemiF-AnnotationPipeline/conf
      - file://SemiF-SyntheticPipeline/conf
      - file://SemiF-InspectCutouts/conf

  run:
    # dir: ./outputs
    
    dir: ${logs.logdir}/${job.jobname}/${general.batch_id}
  output_subdir: 

# Required config. Only change these.
#----------------------------------------------------
general:
  # Do not put key in the config since the file is committed to GitHub
  season: summer_weeds_2022
  metashape_key: ???
  weed_location_shp: weed_locations_2022/weed_locations.shp
#----------------------------------------------------
  batch_id: ??? # NOTE: ??? is a special syntax. Do not remove. Set in shell scripts
  task: ???
  # Main working directory 
  workdir: ${hydra:runtime.cwd}  # where the code is executed

# Other job/naming options (currently not used)
job:
  jobname: ${general.season}
  job_now: &nowdir ${now:%Y-%m-%d}/${now:%H-%M-%S}
  jobdir: ${data.datadir}/${job.jobname}/${job.job_now}

repo_names:
  semif_annotation: SemiF-AnnotationPipeline
  semif_snyth: SemiF-SyntheticPipeline

blob_names: # directory names in SemiF-AP/data that mimic blob container structure
  upload: semifield-upload-images
  developed: semifield-developed-images
  utils: semifield-utils
  cutout: semifield-cutouts
  model: semifield-models
  synth: semifield-synth

# Root data locations (SemiFAnnotationPipeline/data/)
data:
  # Main data folders (replicates blob container naming)
  datadir: ${semif.workdir}/data
  developeddir: ${data.datadir}/${blob_names.developed}
  cutoutdir: ${data.datadir}/${blob_names.cutout}
  modeldir: ${data.datadir}/${blob_names.model}
  utilsdir: ${data.datadir}/${blob_names.utils}
  # Logs
  logdir: ${general.workdir}/logs
  # Batch directory
  batchdir: ${data.developeddir}/${general.batch_id} 
  # All species information
  species: ${data.utilsdir}/species_information/species_info.json
  species_poly: ${data.utilsdir}/autosfm/${general.weed_location_shp}
  # Ground control points directory
  gcp_dir: ${data.datadir}/${blob_names.utils}/autosfm/GroundControlPoints
  gcp_ref: None
  metashape_key_path: ${general.workdir}/keys/metashape_key.txt
  
# Batch sub-directories
batchdata:
  images: ${data.batchdir}/images #preprocessed images
  masks: ${data.batchdir}/masks #blue bbot pixel masks
  plant_dects: ${data.batchdir}/plant-detections # Skovsen et al. pre-inferenced detection if available
  autosfm: ${data.batchdir}/autosfm # asfm batch dir
  metadata: ${data.batchdir}/metadata # metadata created from remap
  meta_masks: ${data.batchdir}/meta_masks # created from segment vegetation
  batchmeta: ${data.batchdir}/${general.batch_id}.json # created from seg veg
  cutouts: ${data.cutoutdir}/${general.batch_id}

logs:
  logdir: ${general.workdir}/.batchlogs
  processed: ${logs.logdir}/processed.txt