# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - movedata: movedata
  - asfm: asfm
  - semif: semif
  - inspect: inspect
# ancillary configs
  - detect: detect
  - segment: segment
  - planting: planting # Planting dates
  - override hydra/job_logging: custom # custom logging 
  - _self_

hydra:
  run:
    # dir: ./outputs
    dir: ${logs.logdir}/${job.jobname}/${general.batch_id}
    # dir: ${logs.logdir}/${job.jobname}
  output_subdir: 

# Required config. Only change these.
#----------------------------------------------------
general:
  # season: summer_weeds_2022
  season: cool_season_covers_2022_2023
#----------------------------------------------------
  metashape_key: ??? # Do not put key in the config since the file is committed to GitHub
  batch_id: ???
  task: ???
  # Main working directory 
  workdir: ${hydra:runtime.cwd}  # where the code is executed

# Other job/naming options (currently not used)
job:
  jobname: ${general.season}
  job_now: &nowdir ${now:%Y-%m-%d}/${now:%H-%M-%S}
  jobdir: ${data.datadir}/${job.jobname}/${job.job_now}

blob_names: # directory names in SemiF-AP/data that mimic blob container structure
  developed: semifield-developed-images
  utils: semifield-utils
  cutout: semifield-cutouts
  model: semifield-models

# temp data locations (SemiFAnnotationPipeline/data/)
data:
  # Main data folders (replicates blob container naming)
  datadir: ${general.workdir}/data
  developeddir: ${data.datadir}/${blob_names.developed}
  cutoutdir: ${data.datadir}/${blob_names.cutout}
  modeldir: ${data.datadir}/${blob_names.model}
  utilsdir: ${data.datadir}/${blob_names.utils}
  # Logs
  logdir: ${general.workdir}/logs
  # Batch directory
  batchdir: ${data.developeddir}/${general.batch_id} 
  # All species information
  species: ${data.utilsdir}/species_information/species_info.json
  species_poly: ${data.utilsdir}/autosfm/ShapeFiles/${general.season}/${general.season}.shp
  # Ground control points directory
  gcp_dir: ${data.datadir}/${blob_names.utils}/autosfm/GroundControlPoints
  gcp_ref: None

pipeline_keys: ${general.workdir}/keys/pipeline_keys.yaml
  
  
# Batch sub-directories
batchdata:
  images: ${data.batchdir}/images #preprocessed images
  masks: ${data.batchdir}/masks #blue bbot pixel masks
  plant_dects: ${data.batchdir}/plant-detections # Skovsen et al. pre-inferenced detection if available
  autosfm: ${data.batchdir}/autosfm # asfm batch dir
  metadata: ${data.batchdir}/metadata # metadata created from remap
  meta_masks: ${data.batchdir}/meta_masks # created from segment vegetation
  batchmeta: ${data.batchdir}/${general.batch_id}.json # created from seg veg
  cutouts: ${data.cutoutdir}/${general.batch_id}

logs:
  logdir: ${general.workdir}/.batchlogs
  processed: ${logs.logdir}/processed.txt
  unprocessed: ${logs.logdir}/unprocessed.txt
