general:
  batch_id: NC_2022-03-11
  save_to_database: False
  db: test  # test, trial, WIR
  multitask: False
  multitasks: [auto_sfm, localize_plants, remap_labels, segment_vegetation]
  task: auto_sfm  # test_mongodb, , segment_vegetation, localize_plants, remap_labels, auto_sfm
  workdir: ${hydra:runtime.cwd}  # where the code is executed
  datadir: ${general.workdir}/data
  batchdir: ${general.datadir}/trial/${general.batch_id}
  imagedir: ${general.batchdir}/developed

detect:
  model_path: ${general.workdir}/models/plant_detector/exp/weights/best.pt
  detections_csv: ${general.batchdir}/detections.csv
  save_detection: False
  detectioncropdir: ${general.imagedir} # Location to save detection crops

autosfm:
  autosfmdir: ${general.batchdir}/autosfm
  # Need not be in the workdir
  config_save_path: ${general.workdir}/autosfm_placeholder/config.yml
  config_copy_path: ${general.workdir}/autosfm_placeholder/config_${general.batch_id}.yml

  autosfm_config:
    # Required config
    export_path: "/home/psi_docker/autoSfM/exports" # Path in the Docker container
    storage_path: "/home/psi_docker/autoSfM/storage" # Path in the Docker container
    batch_id: ${general.batch_id}
    # Electives
    downscale:
      enabled: True
      factor: 0.5 # between (0, 1]

    align_photos:
      downscale: 1 # Accuracy parameter, lower means higher accuracy
      autosave: True

    depth_map:
      enabled: True
      downscale: 4
      autosave: True

    dense_cloud:
      enabled: True
      autosave: True

    dem: 
      enabled: True
      autosave: True

    orthomosaic:
      enabled: True
      export: 
        enabled: True
      autosave: True

    camera_fov:
      enabled: True

segment:  # Segment Vegetation
  clear_border: True
  cutoutdir: ${general.batchdir}/cutouts
  save_mask: False # Not implemented
  vi: exg
  class_algorithm: kmeans
  num_classes: 1
