default:
- db: mongodb
- URI: mongodb://localhost
- database: opencv2021
- collection: image
- _self_

general:
  task: localize_plants # segment_vegetation, localize_plants, CutoutLibrary GenerateMask GenMaskMultiProc SegmentVegetation
  name: test_exp_v2
  workdir: ${hydra:runtime.cwd}/  # where the code is executed
  datadir: ${general.workdir}/data
  autosfm_results: ${general.datadir}/autosfm_results
 
  model_path: ${general.workdir}/models/detection/bs6_imgsz640/weights/best.pt
  
  datetime: &datetime ${now:%Y%m%d_%H%M%S}
  detection_csvpath: ${general.workdir}/runs/detections_${general.datetime}.csv
  
  vi: exg
  class_algorithm: kmeans
  num_classes: 1

  
