name: semif_gpu
channels:
  - pytorch
  - conda-forge
  - conda-forge/label/dev
dependencies:
  - python==3.9
  - pip
  - cudatoolkit=11.3.1
  - pytorch::pytorch
  - pytorch::torchvision
  - geopandas
  - pip:
    - dacite
    - exifread
    - hydra-core
    - matplotlib
    - omegaconf
    - opencv-python
    - numpy
    - pandas
    - pyyaml
    - rasterio
    - requests
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - tqdm
    - pyshp
    - shapely
    - ipykernel